apiVersion: v1
kind: Service
metadata:
  name: devops-service
  labels:
    app: petclinic-app   # Match the labels of your pods
spec:
  selector:
    app: petclinic-app   # Match the labels of your pods
  type: LoadBalancer
  ports:
  - nodePort: 32751
    port: 8080
    targetPort: 8080
